### ISSUE TITLE
Too many seeds

### ISSUE THREAD

**Issue by Slyklaw** [defeatedcrow/HarvestWithDispenser#2]
Harvesting creates a new seed virtually every time. I don't think it should occur that often. I suspect the first seed should be deleted (ie used to replant), and any additional seeds should be kept as harvest results.

**Comment by defeatedcrow** [comment]
This mod is designed as a development of vanilla's automatic harvesting mechanism (water flow, piston). There is no plan to give dispensers a stronger ability than current.
Sorting and deleting harvest items is a new feature and it is the OP that does this with this mod. It is recommended that you use the higher cost other mod machines or make that yourself.

Supplement:
Vanilla items have no way of identifying that they are "seeds" or "crops". There is no exact way to exclude only "seeds" from the block's drop list.

**Comment by Slyklaw** [comment]
Ah, so this is actually how shears work on crops. Thanks for clearing that up.
