### ISSUE TITLE
Compatibility with Agricraft?

### ISSUE THREAD

**Issue by starryknight64** [defeatedcrow/HarvestWithDispenser#3]
Was wondering if this mod could be made compatible with Agricraft crops? Please and thanks!

**Comment by defeatedcrow** [comment]
Sorry, I haven't confirmed it yet. This mod only works with vanilla crop and HaC crop, HC crop. Other mods may work, but I'm not sure.
If you need it, I will consider to add it.

**Comment by starryknight64** [comment]
It's quite close and I know Agricraft implements the IGrowable interface. When I try it, the Dispenser harvests the crop sticks instead of the plant. Thank you so much!

**Comment by defeatedcrow** [comment]
AgriCraft plugin has been added to [v1.0.5](https://github.com/defeatedcrow/HarvestWithDispenser/releases/tag/v1.0.5). Thank you!
